### ISSUE TITLE
Support for openai textgen ie oobagooba?

### ISSUE THREAD

**Issue by XeonG** [yanis-falaki/Fishnet-Helper#1]
I haven't tried this project however did noticed maybe it would possible to use it with a local model running on textgen with the --api it uses openai, not really familiar with python to do it myself... but I saw  https://langchain-git-fork-uetuluk-master-langchain.vercel.app/docs/integrations/llms/textgen  

maybe could add support for that for those who want to run it locally and use a local llm maybe support for other help docs

**Comment by XeonG** [comment]
nevermind.. I just found out you can just use the .env with local textgen localhost ip/api and it does work.. cool project

**Comment by yanis-falaki** [comment]
Great, happy you figured out what you trying to do.
